export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  slug: string;
  price: number;
  compareAtPrice?: number;
  rating: number;
  reviewsCount: number;
  image: string;
  hoverImage: string;
  shortDescription: string;
  description: string;
  inStock: boolean;
  isNew: boolean;
  isFeatured: boolean;
  productType: 'liquid' | 'coating' | 'accessory' | 'kit';
  collections: string[];
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Ultimate Ceramic Coating 9H',
    brand: 'Liquid Plus Professional',
    category: 'Ceramic Coatings',
    slug: 'ultimate-ceramic-coating-9h',
    price: 6500,
    compareAtPrice: 7500,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=600',
    shortDescription: 'Advanced nanotech silane coat forming a high-gloss crystalline layer.',
    description: 'Ultimate Ceramic Coating 9H represents the pinnacle of paint protection chemistry. It creates a molecular bond with clear coats to shield against light scratches, UV rays, acidic rain, and harsh road chemicals.',
    inStock: true,
    isNew: true,
    isFeatured: true,
    productType: 'coating',
    collections: ['nano-tech', 'best-sellers'],
  },
  {
    id: '2',
    name: 'Graphene Coating Pro',
    brand: 'Liquid Plus Professional',
    category: 'Ceramic Coatings',
    slug: 'graphene-coating-pro',
    price: 7800,
    compareAtPrice: 8900,
    rating: 4.9,
    reviewsCount: 86,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1605558191976-9a00b77faac0?q=80&w=600',
    shortDescription: 'Infused with reduced graphene oxide for elite heat and spot resistance.',
    description: 'Our Graphene Coating Pro utilizes premium nano-graphene platelets to provide a high-slickness finish with water contact angle of over 115 degrees, preventing water spots.',
    inStock: true,
    isNew: true,
    isFeatured: true,
    productType: 'coating',
    collections: ['nano-tech'],
  },
  {
    id: '3',
    name: 'HydroFoam Snow Shampoo',
    brand: 'Liquid Plus Core',
    category: 'Car Shampoo',
    slug: 'hydrofoam-snow-shampoo',
    price: 1299,
    rating: 4.8,
    reviewsCount: 96,
    image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?q=80&w=600',
    shortDescription: 'pH-neutral, extreme slickness pre-wash foam to float road grit.',
    description: 'HydroFoam creates thick clingy foam blankets that lift dirt off paint surfaces, reducing scratch risks during wash sponge contact.',
    inStock: true,
    isNew: false,
    isFeatured: true,
    productType: 'liquid',
    collections: ['best-sellers'],
  },
  {
    id: '4',
    name: 'Satin Finish Leather Guard',
    brand: 'Liquid Plus Core',
    category: 'Interior Care',
    slug: 'satin-finish-leather-guard',
    price: 1499,
    rating: 4.7,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1509319117193-57bab727e09d?q=80&w=600',
    shortDescription: 'Cleans, nourishes, and adds UV barriers on premium leather trims.',
    description: 'Leaves a clean, non-greasy satin sheen with authentic leather scent while shielding against dashboard cracking.',
    inStock: true,
    isNew: false,
    isFeatured: true,
    productType: 'liquid',
    collections: ['best-sellers'],
  },
  {
    id: '5',
    name: 'Apex Iron Off Wheel Cleaner',
    brand: 'Liquid Plus Professional',
    category: 'Wheel & Tire Care',
    slug: 'apex-iron-off-wheel-cleaner',
    price: 1850,
    compareAtPrice: 2100,
    rating: 4.9,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1605558191976-9a00b77faac0?q=80&w=600',
    shortDescription: 'Color-changing active chemical melting brake dust on impact.',
    description: 'Apex Iron Off targets baked iron fallout, turning bright purple as it dissolves contaminants on alloy rims safely.',
    inStock: true,
    isNew: false,
    isFeatured: true,
    productType: 'liquid',
    collections: ['best-sellers'],
  },
  {
    id: '6',
    name: 'Ultra Gloss Quick Detailer',
    brand: 'Liquid Plus Core',
    category: 'Exterior Care',
    slug: 'ultra-gloss-quick-detailer',
    price: 1150,
    rating: 4.8,
    reviewsCount: 72,
    image: 'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600',
    shortDescription: 'Spray and wipe gloss enhancer and clay lubricant formula.',
    description: 'Perfect for removing light dust and fingerprints, adding immediate depth, shine, and minor hydrophobic beading.',
    inStock: true,
    isNew: false,
    isFeatured: true,
    productType: 'liquid',
    collections: ['best-sellers'],
  },
  {
    id: '7',
    name: 'Clay Bar Detailing Prep Kit',
    brand: 'Liquid Plus Accessories',
    category: 'Exterior Care',
    slug: 'clay-bar-detailing-prep-kit',
    price: 950,
    rating: 4.5,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1627124718133-0112dec7a6a4?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600',
    shortDescription: 'Medium-grade detailing clay bar pack with plastic storage case.',
    description: 'Removes industrial fallout, tree sap, overspray, and bonded contaminants to create glass-smooth paint surfaces.',
    inStock: false,
    isNew: false,
    isFeatured: false,
    productType: 'kit',
    collections: [],
  },
  {
    id: '8',
    name: 'Ceramic Tyre Dressing',
    brand: 'Liquid Plus Professional',
    category: 'Wheel & Tire Care',
    slug: 'ceramic-tyre-dressing',
    price: 1650,
    rating: 4.8,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1509319117193-57bab727e09d?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600',
    shortDescription: 'Cures to dry-to-the-touch deep black shine with water repellency.',
    description: 'An advanced ceramic dressing that does not fling off onto body panels, preventing rubber browning for weeks.',
    inStock: true,
    isNew: false,
    isFeatured: true,
    productType: 'liquid',
    collections: ['best-sellers'],
  },
  {
    id: '9',
    name: 'Crystal Clear Glass Cleaner',
    brand: 'Liquid Plus Core',
    category: 'Glass Care',
    slug: 'crystal-clear-glass-cleaner',
    price: 899,
    rating: 4.7,
    reviewsCount: 48,
    image: 'https://images.unsplash.com/photo-1605558191976-9a00b77faac0?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600',
    shortDescription: 'Ammonia-free glass cleaner leaving zero residue or haze streaks.',
    description: 'Safe for tinted windows. Easily cuts through road film, bug splatters, vinyl haze, and smoke deposits.',
    inStock: true,
    isNew: false,
    isFeatured: false,
    productType: 'liquid',
    collections: [],
  },
  {
    id: '10',
    name: 'Premium Microfiber Towel Pack',
    brand: 'Liquid Plus Accessories',
    category: 'Accessories',
    slug: 'premium-microfiber-towel-pack',
    price: 1100,
    rating: 4.8,
    reviewsCount: 92,
    image: 'https://images.unsplash.com/photo-1509319117193-57bab727e09d?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600',
    shortDescription: 'Edgeless, high-pile 600 GSM microfiber cloths for scratch-free buffs.',
    description: 'Perfect for buffing waxes, sealants, quick detailers, or interior cleaning jobs safely.',
    inStock: true,
    isNew: false,
    isFeatured: false,
    productType: 'accessory',
    collections: [],
  },
  {
    id: '11',
    name: 'Microfiber Applicator Blocks',
    brand: 'Liquid Plus Accessories',
    category: 'Accessories',
    slug: 'microfiber-applicator-blocks',
    price: 490,
    rating: 4.6,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1627124718133-0112dec7a6a4?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=600',
    shortDescription: 'Soft foam core blocks wrapped in fine microfiber threads.',
    description: 'Ideal for laying ceramic coatings, glazes, dressings, or wax coatings onto delicate paint panels.',
    inStock: true,
    isNew: false,
    isFeatured: false,
    productType: 'accessory',
    collections: [],
  },
  {
    id: '12',
    name: 'Ultimate Detailing Master Kit',
    brand: 'Liquid Plus Professional',
    category: 'Detailing Kits',
    slug: 'ultimate-detailing-master-kit',
    price: 12500,
    compareAtPrice: 14500,
    rating: 4.9,
    reviewsCount: 54,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600',
    hoverImage: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=600',
    shortDescription: 'Full collection of shampoos, coatings, detailers, and applicators.',
    description: 'The complete detailing arsenal for professionals. Contains Ceramic Coating 9H, Snow Shampoo, Leather Guard, Glass Cleaner, Towels, and Applicator blocks.',
    inStock: true,
    isNew: true,
    isFeatured: true,
    productType: 'kit',
    collections: ['nano-tech'],
  },
];
